### ISSUE TITLE
EDC API Clients

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#177]
# Initiative

## Description

Use Cases use the the EDC API and thus need API clients.

Difficulties of using the existing Data Management API models for auto generation of api clients and concerns about the sufficiency of existing Data Management API endpoints causes each use case to implement its own API Client while having to do multiple API calls to create a single data offering, etc.

Because of that we are extending the data management API with our own API endpoints and models.

With these new models and endpoints tailored for auto generation we could do multiple things:

- Have API clients in both TypeScript, Java and potentially other languages that are mostly automatically generated, allowing us to ship changes faster and thus confidently change things.
- We could work around API changes that might come from changes between  milestones.
- We could offer a simpler and more opinionated workflow for working with the EDC.

### Requirements

- [ ] Are there any parts of the implementation that should wait for the EDC MS 9?

## Work Breakdown

- [ ] Architecture & POC
  - [ ] Bootstrap Extension
  - [ ] Dummy API Endpoint
  - [ ] OpenAPI Generation
  - [ ] OpenAPI Generation should contain documentation
  - [ ] OpenAPI Generation needs to contain correct nullability
  - [ ] POC Java API Client
    - microprofile-rest-client might generate the client from JAX-RS annotated interfaces
  - [ ] OpenAPI Serving in dev
  - [ ] SwaggerUI Serving in dev
  - [ ] POC TypeScript API Client
- [ ] EDC API Clients for Use Cases
  - [ ] createOffering(asset, policy, contract)
  - [ ] updateOffering
  - [ ] consume (assetId, contractDefId, dataDestination)
  - [ ] catalog (connectorEndpoints)
  - [ ] Possibly other endpoints for the Silicon Economy EDC API
- [ ] EDC UI API with Backend-For-Frontend
  - [ ] Contract Agreement List
  - [ ] Do we want to absorb the "contract-agreement-transfer-api" extension?
  - [ ] Decide next/other pages to be migrated to Backend-For-Frontend.
- [ ] EDC Usability Extensions to be contained in the API Clients
  - [ ] CRUD known Connectors (reuse existing extension from registrationservice?)
  - [ ] KPI endpoint
  - [ ] Registered policies endpoint

### Hypothesis

- Using auto generated API clients saves time and effort.
- Adjusting to milestone changes once in this extension takes less time and effort than adjusting consumers of our EDC APIs.
- Building this extension as cooperation between the ISST and sovity while letting the extension contain both EDC UI and Use Case API Endpoints will allow all of us to save time in both the initial implementation and when migrating to newer milestones.

## Acceptance criteria and must have scope

- [ ] Workflows Consume and Provide must work in at least the Java Client.
- [ ] Changes that don't include adding API Endpoints should not require any changes in the code for API Clients.

## Stakeholders

- Sovity is interested in the API Wrapper to offer it as convenience for its potential customers.
- Sovity's next use case application might use this Java Client if it's ready.
- The ISST wants to be able to use the API Wrapper as Java Client for the
  Silicon Economy EDC while thinking about potentially using other existing endpoints to easily provide more value e.g. KPIs/metrics for a dashboard, etc.

## Timeline

- Staring with Implementation starting 13.03.2023
  - Detailed planned timeline TBA
- Upon new EDC milestones we shall wait for 1-4 weeks to let initial bugs settle before we migrate the code to the newer milestone while dropping support for the previous milestone.

**Comment by richardtreier** [comment]
![api-wrapper drawio](https://user-images.githubusercontent.com/30114507/224313781-f971056e-9c83-421a-bcae-098ecb627bcb.png)

**Comment by SebastianOpriel** [comment]
- [ ] sovity/edc-ui#98
