### ISSUE TITLE
POC & Architecture for EDC API Wrapper and Clients

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#181]
# Epic

## Description

Our Initiative https://github.com/sovity/edc-extensions/issues/177 requires setup of the extension and a first working example before implementation in parallel can begin.

### MVP
- [x] #187
- [x] https://github.com/sovity/edc-extensions/issues/184
- [x] https://github.com/sovity/edc-extensions/issues/185
- [x] #190
- [x] #285 

### Future to be implemented separately (but tracked by this issue)
- [ ] #284 
- [ ] #210 
- [ ] #188
- [ ] #189
- [ ] #186

## Initiative / goal

To implement our API Wrapper which serves multiple clients there are certain tasks that need to be done for the sake of all of them.

## Acceptance criteria and must have scope

- [ ] Java API Client Library working with all auth methods integrated into CD 
- [ ] For UI: Typescript API Client Library working with all auth methods integrated into CD
