### ISSUE TITLE
EDC UI API

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#183]
# Epic

## Description

With our highly agile EDC API Wrapper and EDC API Clients underway the goal is to have a Backend-For-Frontend API, just for our UI.

With our generated TypeScript Client we can iterate quickly and thus confidently build, adopt and iterate our own UI APIs, slowly retiring the Data Management API, one page at a time.

### Requirements

Requires TypeScript Client: https://github.com/sovity/edc-extensions/issues/185

## Work Breakdown

- [ ] New Contract Agreement Page: https://github.com/sovity/edc-extensions/issues/243
- [ ] New Transfer History Page: https://github.com/sovity/edc-ui/issues/98
- [ ] ...

## Initiative / goal

We will be able to develop new UI functionality, adopt simplified workflows, and show the data where we desire in what quantity. In general, we can take the UX to a next level and retire the UX of the old EDC DataDashboard.

### Hypothesis

- Having control over our API will allow us to add an edge with better UX.
- Having good UX is good for our business.

## Acceptance criteria and must have scope

- [ ] Successful consumption in EDC UI

## Stakeholders

EDC UI / our CaaS

## Need for refinement

- Which pages do we want to migrate? Which ones first?

**Comment by SebastianOpriel** [comment]
superseded by https://github.com/sovity/edc-ui/issues/175
