### ISSUE TITLE
TypeScript API Wrapper Client with OAUTH2

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#284]
# Feature Request

## Description

Right now the API wrapper works for the EDC Community Edition, our UI, but not for clients of our CaaS, as we are currently providing them with OIDC credentials.

## Which Areas Would Be Affected?

API Wrapper: TS API Client

## Stakeholders

CaaS customers

## Solution Proposal and Work Breakdown
- Our Java implementation: https://github.com/sovity/edc-extensions/tree/main/extensions/wrapper/clients/java-client/src/main/java/de/sovity/edc/client/oauth2
- The TS implementation does not need to be custom, but the library should not add too much weight.

```[tasklist]
### Tasks
- [ ] Implement OAuth2 Client Credentials Auth to authenticate against our production CaaS / Enterprise Edition EDCs. See https://github.com/sovity/edc-extensions/issues/285
- [ ] Test the API Client Library against a productive sovity EDC connector.
- [ ] Add documentation to the TS API Client Library similar to the Java API Client Library
- [ ] Add Tutorial in Zammad
```

**Comment by richardtreier** [comment]
already implemented by @kulgg
