### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#369]
# Release

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:
- [x] Release [edc-ui](https://github.com/sovity/edc-ui), this might require several steps.
- [x] Decide a release version depending on major/minor/patch changes in the CHANGELOG.md.
- [x] Update this issue's title to the new version
- [x] `release-prep` PR:
  - [x] Update the CHANGELOG.md.
    - [x] Add a clean `Unreleased` version.
    - [x] Add the version to the old section.
    - [x] Add the current date to the old version.
    - [x] Write or review the `Deployment Migration Notes` section.
    - [x] Write or review a release summary.
    - [x] Remove empty sections from the patch notes.
  - [x] Replace the existing `docker-compose.yaml` file from `docker-compose-dev.yaml`.
  - [x] Remove the second connector from the `docker-compose.yaml` file.
  - [x] Rename the `${DEV_*}` variables with their `${RELEASE_*` counterparts.
  - [x] Set the version for `RELEASE_EDC_IMAGE` of the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
  - [x] Set the UI release version for `RELEASE_EDC_UI_IMAGE` of the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
  - [x] If the core EDC version changed, update the `openapi.yaml`.
  - [x] Update the Postman Collection if required.
  - [x] Merge the `release-prep` PR.
- [x] Test the release `docker-compose.yaml` with `RELEASE_EDC_IMAGE=ghcr.io/sovity/edc-dev:latest`.
- [x] Test the postman collection against that running docker-compose.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [x] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [x] Revisit the changed list of tasks and compare it with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/edc-extensions/blob/main/.github/ISSUE_TEMPLATE/bug_report.md). Propose changes where it
  makes sense.
