### ISSUE TITLE
Investigate EDC0 for known MS8 issues

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#387]
# Feature Request

## Description

There's a few things we waited for EDC 0.1.0 to either validate as fixed, (re-)create as issues or implement workarounds for.

## Work Breakdown

- [x] depends on https://github.com/sovity/edc-extensions/issues/391
- [x] Check our EDC with Core EDC >0 for the following issues:
  - [x] PosgreSQL error when querying >5k results.
  - [x] N+1 SELECT problem affecting transfer processes (slowdown of >10s / 50 data offers)
    - Seems to be fixed for now. A connector with data offers 1, 50, 80 and 500 all average about 3-4s for transfer processes.
  - [x] N+1 SELECT problem affecting catalog (slowdown of >10s / 50 data offers)
    - Seems to persist. 500 assets take 12s on local machine without DB latency.
    -  Core EDC has positioned themselves against this issues in favor of Web-DIDs and the Federated Catalog which would periodically crawl ALL connectors in a data space.
  - [x] No clear quantity structure supported by EDC. EDC is tested with in-memory stores. Moved into initiative https://github.com/sovity/PMO-Software/issues/536
  - [x] Contract Negotiation does not persist asset information at time of negotiation agreement. Moved into issue https://github.com/sovity/edc-extensions/issues/336
  - [x] Possibly breaking changes in persistence that cannot be dealt with, or cannot be easily dealt with with database migrations.
  - [x] Validate Connector ID concept for consistency (see Management API Transfer History endpoint, for example)
  - [x] The MS8 Connector's Contract Negotiations fail in HTTPS-only environments. See https://github.com/sovity/edc-extensions/issues/379
  - [x] Transfer Processes don't get put into the state COMPLETED on the providing side.
  - [x] Investigate an old issue where the number of contract offers grew with `numAssets to the power of numContractDefinitions`.
  - [x] Data consistency issues. Moved into issue https://github.com/sovity/edc-ui/issues/462
  - [x] Check EDC 0 Capabilities for tracing (?) logging. Logging has been improved with configurable dev logging. Tracing is used in the EE, but not the CE as of now.
- [x] Create Issues to either ignore, fix or workaround the above issues.

**Comment by richardtreier** [comment]
Findings of @efiege on a local machine (no latency to db):

```
2 Assets:
Catalog retrieve took milliseconds: 525
Transfer took milliseconds: 2525

51 Assets:
Catalog retrieve took milliseconds: 5855
Transfer took milliseconds: 3013

81 Assets:
Catalog retrieve took milliseconds: 3279
Transfer took milliseconds: 4203

501 Assets:
Catalog retrieve took milliseconds: 12975
Transfer took milliseconds: 3638
```

**Comment by dcarmen1** [comment]
Hi! 

I wanted to ask about the status of the issue [387]. I understand that you're likely handling a multitude of tasks, but I'm curious if there have been any updates or progress made regarding the request.

Thank you for the help.

**Comment by richardtreier** [comment]
> I wanted to ask about the status of the issue [387]. I understand that you're likely handling a multitude of tasks, but I'm curious if there have been any updates or progress made regarding the request.

Hi, our migration to EDC 0.x is still underway, albeit at a very high priority. 

At this point we aren't ready yet to test all of the above points as we are still migrating core functionalities.

If you want to track our progress on our EDC 0.x migration, feel free to check out our issues:
- https://github.com/sovity/edc-extensions/milestone/1
- https://github.com/sovity/edc-ui/issues/364

**Comment by dcarmen1** [comment]
Hi, regarding the status of issue [387] I'm eager to know if there have been any updates or progress made concerning the request, is the implementation inside of the new connector version?
Thank you

**Comment by tmberthold** [comment]
> Hi, regarding the status of issue [387] I'm eager to know if there have been any updates or progress made concerning the request, is the implementation inside of the new connector version? Thank you

Are you looking for a specific point in this issue? We have migrated to core-edc 0.2.1 in the meanwhile, for example this core-edc version is used in out last CE: https://github.com/sovity/edc-extensions/releases/tag/v7.1.1

**Comment by dcarmen1** [comment]
Yes I was looking for this point: The MS8 Connector's Contract Negotiations fail in HTTPS-only environments

**Comment by richardtreier** [comment]
Issues have been split where appliccable or marked as completed.
