### ISSUE TITLE
 EDC 0.2.x Migration in edc-extensions

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#391]
# Feature Request

## Description

Upgrade from MS8 to Core EDC 0.1.x

```[tasklist]
### Tasks
- [x] Create tests that test DB migrations by inserting MS8 data and testing functionality in 0.1.0:
- [x] Test: Consumed Data Offer Metadata
- [x] Test: Provided Data Offer Metadata including Transfer Processes
- [x] Test: Test data exchange (both roles)
- [x] Asset Properties have been changed. Before there were special asset properties referenced in the Asset class. Those we should migrate.
- [x] Write DB Migration Scripts
- [x] Fix `/ids` endpoints to `/dsp` endpoints
- [x] Migrate Docker Compose
- [x] Migrate `connector/.env`
- [x] Migrate Postman Collection
- [x] Migrate OpenAPI Yamls
- [x] Write Migration Notes for Deployments
- [x] Integrate `main`-Branch changes into 0.2.x-Branch
- [x] Check for Database-Entity changes in the core EDC and interate them in the Flyway-DB-Migration-Extension
- [x] Decide if `EDC_JSONLD_HTTPS_ENABLED` should be turned on to resolve JSON-LD Schemata. Decided to turn it on for now
- [x] If not turned on: Integrate an Extension, that brings the JSON-LD Schemata with it like Catena did it: https://github.com/eclipse-tractusx/tractusx-edc/tree/main/core/json-ld-core Preliminary: We should allow all JSON and disable validation
- [ ] https://github.com/sovity/edc-extensions/issues/387
```
