### ISSUE TITLE
Check and rework HTTPProxy flow and documentation

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#482]
# Bug Report

## Description

- Our current [HTTPProxy documentation](https://github.com/sovity/edc-extensions/blob/main/docs/getting-started/documentation/pull-data-transfer.md)
- Old Core EDC diagram: https://github.com/eclipse-edc/Connector/blob/099c126849b6817e380a2e0f85a2037a093849e0/docs/developer/architecture/data-transfer/diagrams/transfer-data-plane-consumer-pull.png
- New Core EDC diagram: https://github.com/eclipse-edc/Connector/blob/77e68dc8322d2e872073d7bec3b0f7fe3e26e78f/docs/developer/architecture/data-transfer/diagrams/transfer-data-plane-consumer-pull.png

```[tasklist]
### Tasks
- [ ] Check out the three documentations. Has the flow changed?
- [x] Adjust Documentation
- [x] Adjust postman collection (if required)
- [ ] Add E2E Tests for HTTPProxy flow to have regression tests across versions
- [x] Are there other sources of documentation we need to change?
- [x] Adjust https://github.com/sovity/edc-extensions/blob/main/docs/getting-started/documentation/pull-data-transfer.md for EDC 0
```
