### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-extensions#561]
# Release

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:

- [x] Release [edc-ui](https://github.com/sovity/edc-ui), this might require several steps: https://github.com/sovity/edc-ui/releases/tag/v2.0.0
- [x] Decide a release version depending on major/minor/patch changes in the CHANGELOG.md.
- [x] Update this issue's title to the new version
- [x] `release-prep` PR:
    - [x] Write or review the current [Productive Deployment Guide](https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/production)
    - [x] Write or review the current [Development Deployment Guide](https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/development)
    - [x] Write or review the current [Local Demo Deployment Guide](https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/local-demo)
    - [x] For Major version updates: If we want to continue supporting the old major version:
        - [x] Keep the old Productive Development Guide in a separate location.
            - [x] Add a note to the old version about its deprecation status.
            - [x] Add a Link the old version in the new version for discoverability.
            - [x] Check all links in the old version.
        - [x] Keep the old Local Demo Development Guide in a separate location.
            - [x] Add a note to the old version about its deprecation status.
            - [x] Add a Link the old version in the new version for discoverability.
            - [x] Check all links in the old version.
    - [ ] Update the CHANGELOG.md.
        - [x] Add a clean `Unreleased` version.
        - [x] Add the version to the old section.
        - [x] Add the current date to the old version.
        - [x] Check the commit history for commits that might be product-relevant and thus should be added to the
          changelog. Maybe they were forgotten.
        - [x] Write or review the `Deployment Migration Notes` section, check the commit history for changed / added
          configuration properties.
        - [x] Write or review a release summary.
        - [x] Write or review the compatible versions section.
        - [x] Add a link to the EDC UI Release to the "EDC UI" section.
        - [x] Remove empty sections from the patch notes.
    - [x] Replace the existing `docker-compose.yaml` with `docker-compose-dev.yaml`.
    - [x] Set the version for `EDC_IMAGE` of
      the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
    - [x] Set the version for `TEST_BACKEND_IMAGE` of
      the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
    - [x] Set the UI release version for `EDC_UI_IMAGE` of
      the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
    - [x] If the core EDC version changed, update the `openapi.yaml`.
    - [x] Update the Postman Collection if required.
    - [x] Merge the `release-prep` PR.
- [x] Wait for the main branch to be green.
- [x] Test the release `docker-compose.yaml` with `RELEASE_EDC_IMAGE=ghcr.io/sovity/edc-dev:latest`.
- [x] Test the postman collection against that running docker-compose.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [x] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [x] Revisit the changed list of tasks and compare it
  with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/edc-extensions/blob/main/.github/ISSUE_TEMPLATE/release.md).
  Propose changes where it
  makes sense.
- [x] Close this issue.
