### ISSUE TITLE
GitBook: EDC Documentation

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-extensions#594]
# Task

## Description

Refer to epic https://github.com/sovity/edc-extensions/issues/389

## Which Areas Would Be Affected?

Documentation @tmberthold based on the One Note insights that SO shared, please list which part of the documentation is affected

## Solution Proposal and Work Breakdown

```[tasklist]
- [x] Get to know GitBook
- [x] Transfer documentation structure from sovity OneNote to edc-extensions
- [x] Add blank documentation pages where no documentation can be linked (edc-extensions)
- [ ] https://github.com/sovity/edc-extensions/issues/624
- [x] Complete comparison between GitHub Pages and Gitbook for final decision on which tool we use.
- [ ] https://github.com/sovity/edc-extensions/issues/685
```

**Comment by tmberthold** [comment]
Link to OneNote: https://sovity.sharepoint.com/sites/sovity/_layouts/15/Doc.aspx?sourcedoc={d0048dd9-82ab-4bf7-908a-e840b4091ba1}&action=edit&wd=target%28Product.one%7C3efc73fe-bcb5-4108-be39-c9c5573820e6%2FDocumentation%20EDC%20Structure%7Cd1cb653f-4af0-426e-aea3-34a99ae2ed9c%2F%29&wdorigin=NavigationUrl

**Comment by tmberthold** [comment]
Current upcoming structure (wip): https://github.com/sovity/edc-extensions/blob/documentation_refactoring/SUMMARY.md

**Comment by tmberthold** [comment]
As decided in the last sprint, we will stick with GitBook. On the one hand, we are familiar with using GitBook and on the other hand, there are no apparent advantages to the alternative so that a new construction would make sense.

**Comment by tmberthold** [comment]
Documentation is a highly discussed topic but we have made great and valuable progress since the issue was originally created. The issue itself should be outdated by now.
