### ISSUE TITLE
Implement ability to update asset meta data

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-extensions#606]
# Feature Request

## Description

As a USER of the EDC, I want to edit my asset's meta data, so I can keep the assets up-to-date or correct typos/ incorrect information in the description.

*Delivery Date to MDS: 15.02.2024*

## Which Areas Would Be Affected?

- Solution should be implemented across all variants of the sovity CaaS EDC (sovity, MDS, Catena). Not only MDS variant. 
- Solution should be implemented across all subscription tiers of the sovity CaaS EDC (CE?, Basic, Professional, Enterprise). **_TBC with stakeholders._**

## Why Is the Feature Desired?

As a user of the EDC I do not want to delete an asset and create a new one to change the description.

_What problems does that user face that existing functionalities do solve?_

As-Is Situation:
- User does not have the possibility to edit an asset.
- When a user wants to add additional information to an existing asset, user needs to delete the existing version of the asset and create a new asset.

## How does this tie into the current product?

_Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

- Solution for this feature will be an enhancement to the UX of the existing asset management in sovity CaaS EDC.
- Solution is technical feasible based on the insights gathered in https://github.com/sovity/edc-ui/issues/400

## Stakeholders
- MDS
- @jkbquabeck 
- @SebastianOpriel 
- @sebk46 

## Solution Proposal and Work Breakdown

- The EDC supports updates of assets, but these only affect the new contracts. Old contracts won't be updated.
- If the above is a blocker, the solutions are heavy:
  - Connect connectors to the broker and let them update data offers, dysfunctional since contracts can exist for non-available data offers.
  - Let connectors crawl other connectors directly, dysfunctional since contracts can exist for non-available data offers.
  - Let connectors crawl each other OR let connectors update each other on changes, will require custom DSP messages.

```[tasklist]
### EDC Extensions / API Wrapper
- [x] Add update asset endpoint (should be easy), will probably require some work on the UiAssetMapper
- [ ] https://github.com/sovity/edc-extensions/pull/689
```

```[tasklist]
### Connector UI
- [x] Make the Asset Detail Dialog to allow asset editing (should be semi-easy thanks to angular forms)
- [x] Asset Edit Action on each asset in the Asset Page
- [ ] https://github.com/sovity/edc-ui/pull/617
```

**Comment by SebastianOpriel** [comment]
Relates to https://github.com/sovity/edc-ui/issues/400

**Comment by richardtreier** [comment]
Notes regarding estimation:
![grafik](https://github.com/sovity/edc-extensions/assets/30114507/7b53f68c-d906-4046-8ea5-9ae691285783)

**Comment by ip312** [comment]
Prio 1 for the MDS 2.0.
