### ISSUE TITLE
[Gitbook] Create Content for empty documentation pages

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-extensions#624]
**Goal of the task:** compile content for empty pages on GitBook.

```[tasklist]
- [ ] https://github.com/sovity/edc-extensions/issues/684
- [ ] https://github.com/sovity/edc-extensions/issues/693
- [ ] https://github.com/sovity/edc-extensions/issues/694
- [ ] https://github.com/sovity/edc-extensions/issues/695
- [ ] https://github.com/sovity/edc-extensions/issues/696
- [ ] https://github.com/sovity/edc-extensions/issues/697
- [ ] https://github.com/sovity/edc-extensions/issues/698
- [ ] https://github.com/sovity/edc-extensions/issues/699
- [ ] https://github.com/sovity/edc-extensions/issues/700
```

**Comment by AbdullahMuk** [comment]
@tmberthold I created this issue so that we have an overview of the pages where you require content to complete GitBook documentation. Let's use this issue to drive sourcing of the missing contents from relevant colleagues.

Please complete the tasklist with the pages where you require content from others; if possible, name the team or the colleague from whom you require the content.

**Comment by tmberthold** [comment]
Open topics are marked with a TODO here in the overview: https://github.com/sovity/edc-extensions/blob/documentation_refactoring/SUMMARY.md?plain=1

**Comment by tmberthold** [comment]
@AbdullahMuk Updates the list above to reflect the open TODOs/empty pages

**Comment by AbdullahMuk** [comment]
Requires alignment on whether we will keep gitbook; if not, where should the content of gitbook be made available to users and is GH sufficient?

@AbdullahMuk

**Comment by tmberthold** [comment]
Documentation is a highly discussed topic but we have made great and valuable progress since the issue was originally created. The issue itself should be outdated by now.
