### ISSUE TITLE
[Gitbook] Roadmap

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-extensions#684]
```[tasklist]
### Tasks
- [ ] Align on scope of roadmap communication with SK / SO
- [ ] Export roadmap from GH into a medium that can be shared publicly (PPT Slide)
- [ ] Handover roadmap format to TB for publishing on GH
```

**Comment by tmberthold** [comment]
I think the topic is now outdated, as dynamic as we are
