### ISSUE TITLE
Add additional meta information

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#7]
# Feature Request

## Type of Issue
Enhancement

## Describe the ideal solution or feature request
Additional fields, visible to the MDS EDC UI shall be added to the Metadata Broker extension.

## Which Areas Would Be Affected?
[Message Payloads](https://github.com/sovity/edc-broker-extension/blob/1ed5d4cb71e7fa297ee8bd2692408dd4a024190c/extensions/catalog-transfer-extension/src/main/java/sender/RegisterResourceRequestSender.java#L60) of Broker asset registration messages of EDC Broker Extension.

## Why Is the Feature Desired?
Alignment of EDC UI capabilities with other extensions.

## Solution Proposal
Use provided information, to set according fields in asset description. Please find below an example of a Resource Description at Broker from https://catalog.test.mobility-dataspace.eu/resources/resource?id=https%3A%2F%2Fbroker.test.mobility-dataspace.eu%2Fcatalog%2F-1257235213%2F-439825952%2F1892951068

```json
{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/"
  },
  "@type" : "ids:Resource",
  "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068",
  "ids:created" : {
    "@value" : "2022-12-08T10:25:00.311Z",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  },
  "ids:version" : "1",
  "ids:language" : [ {
    "@type" : "ids:Language",
    "@id" : "https://w3id.org/idsa/code/EN"
  } ],
  "ids:resourceEndpoint" : [ {
    "@type" : "ids:ConnectorEndpoint",
    "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068/-1664286248",
    "ids:endpointDocumentation" : [ {
      "@id" : "https://github.com/Mobility-Data-Space/mobility-data-space/wiki/MDS-Ontology"
    } ],
    "ids:accessURL" : {
      "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068"
    },
    "http://www.w3.org/2002/07/owl#sameAs" : {
      "@id" : "https://w3id.org/idsa/autogen/connectorEndpoint/4700dfe4-5723-49a4-a62b-6a0f38707269"
    }
  } ],
  "ids:representation" : [ {
    "@type" : "ids:Representation",
    "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068/-1493557143",
    "ids:created" : {
      "@value" : "2022-12-08T10:25:01.448Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "ids:language" : {
      "@type" : "ids:Language",
      "@id" : "https://w3id.org/idsa/code/EN"
    },
    "ids:mediaType" : {
      "@type" : "ids:IANAMediaType",
      "@id" : "https://w3id.org/idsa/autogen/iANAMediaType/2c0a78df-b103-45f7-b652-f5d9acbcc81d",
      "ids:filenameExtension" : "text/plain"
    },
    "ids:modified" : {
      "@value" : "2022-12-08T10:25:01.448Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "ids:instance" : [ {
      "@type" : "ids:Artifact",
      "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068/-1493557143/-287640995",
      "ids:byteSize" : 79099,
      "ids:creationDate" : {
        "@value" : "2022-12-08T10:25:01.686Z",
        "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
      },
      "ids:checkSum" : "711729741",
      "ids:fileName" : "Stop_Times.txt",
      "http://www.w3.org/2002/07/owl#sameAs" : {
        "@id" : "https://dataspaceconnector:8080/api/artifacts/384992c5-2f4b-4664-9f96-f7ef1ea0c703"
      }
    } ],
    "http://www.w3.org/2002/07/owl#sameAs" : {
      "@id" : "https://dataspaceconnector:8080/api/representations/b43754d8-2e39-4ce9-a544-c6399e9fddd9"
    }
  } ],
  "ids:contractOffer" : [ {
    "@type" : "ids:ContractOffer",
    "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068/-575473219",
    "ids:permission" : [ {
      "@type" : "ids:Permission",
      "@id" : "https://broker.test.mobility-dataspace.eu/catalog/-1257235213/-439825952/1892951068/-575473219/2093720462",
      "ids:title" : [ {
        "@value" : "",
        "@type" : "http://www.w3.org/2001/XMLSchema#string"
      } ],
      "ids:description" : [ {
        "@value" : "",
        "@type" : "http://www.w3.org/2001/XMLSchema#string"
      } ],
      "ids:action" : [ {
        "@type" : "ids:Action",
        "@id" : "https://w3id.org/idsa/code/USE"
      } ],
      "http://www.w3.org/2002/07/owl#sameAs" : {
        "@id" : "https://dataspaceconnector:8080/api/rules/4d173dba-bbfa-4b69-a756-97345535df1e"
      }
    } ],
    "ids:contractStart" : {
      "@value" : "2022-12-08T00:00:00.000Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "ids:contractEnd" : {
      "@value" : "2022-12-31T00:00:00.000Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "ids:contractDate" : {
      "@value" : "2022-12-08T10:25:02.354Z",
      "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
    },
    "http://www.w3.org/2002/07/owl#sameAs" : {
      "@id" : "https://dataspaceconnector:8080/api/contracts/7a62f208-53bb-48e8-9cb3-81d3b51b62d9"
    }
  } ],
  "ids:title" : [ {
    "@value" : "Test Case",
    "@language" : "en"
  } ],
  "ids:description" : [ {
    "@value" : " Test case for the DFRS Workshop",
    "@language" : "en"
  } ],
  "ids:keyword" : [ {
    "@value" : "Test",
    "@language" : "en"
  }, {
    "@value" : "DFRS",
    "@language" : "en"
  } ],
  "ids:standardLicense" : {
    "@id" : "https://creativecommons.org/licenses/by/4.0/"
  },
  "ids:paymentModality" : {
    "@type" : "ids:PaymentModality",
    "@id" : "https://w3id.org/idsa/code/FREE"
  },
  "ids:modified" : {
    "@value" : "2022-12-08T10:25:00.311Z",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  },
  "ids:publisher" : {
    "@id" : "https://mobility-dataspace.eu"
  },
  "http://www.w3.org/2002/07/owl#sameAs" : {
    "@id" : "https://dataspaceconnector:8080/api/offers/5033ca17-3eb7-447e-a583-44d7a56ad030"
  },
  "http://w3id.org/mds#transportMode" : {
    "@value" : "Road",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  },
  "http://w3id.org/mds#dataCategory" : {
    "@value" : "Traffic Information",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  },
  "http://w3id.org/mds#dataSubcategory" : {
    "@value" : "Hazard Warnings",
    "@type" : "http://www.w3.org/2001/XMLSchema#string"
  }
}
```

**Comment by richardtreier** [comment]
Create Asset payload (frontend builds it and thus decides properties):

```json
{
    "asset": {
        "properties": {
            "edcc:id": "urn:artifact:asd",
            "ids:id": "https://originator-undefined-in-edc-ui/assets/urn:artifact:asd",
            "ids:name": "asd",
            "ids:version": "133.7",
            "ids:originator": null,
            "ids:keyword": "test, second",
            "ids:mediaType": "application/idc",
            "ids:description": "desc",
            "ids:language": "ISO_639:EN",
            "ids:publisher": "http://gtfo",
            "ids:standardLicense": "http://gtfo",
            "ids:endpointDocumentation": "http://gtfo",
            "http://w3id.org/mds#dataCategory": "RoadworksRoadConditions",
            "http://w3id.org/mds#dataSubcategory": "Roadworks",
            "http://w3id.org/mds#dataModel": "asd",
            "http://w3id.org/mds#geoReferenceMethod": "asd",
            "http://w3id.org/mds#transportMode": "Road"
        }
    },
    "dataAddress": {
        "properties": {
            "type": "HttpData",
            "baseUrl": "http://gtfo"
        }
    }
}
```

**Comment by omarsilva1** [comment]
The link in the issue description isn't working. The resource was probabely unregistered.

**Comment by richardtreier** [comment]
The asset property names have changed:
- Asset Property names now use "asset:prop:" prefixes to demonstrate we are in EDCC Namespace.
- IDS id will have to be generated by IDS Protocol Implementation.
- ```ts
  
  // edc asset properties
  id: "asset:prop:id", // needs to start with urn:artifact:
  name: "asset:prop:name",
  contentType: "asset:prop:contenttype",
  originator: "asset:prop:originator",
  description: "asset:prop:description",
  version: "asset:prop:version",

  // our asset properties
  keywords: "asset:prop:keyword",
  originatorOrganization: "asset:prop:originatorOrganization",
  language: 'asset:prop:language',
  publisher: "asset:prop:publisher",
  standardLicense: "asset:prop:standardLicense",
  endpointDocumentation: "asset:prop:endpointDocumentation",

  // mds specific asset properties
  dataCategory: 'http://w3id.org/mds#dataCategory',
  dataSubcategory: 'http://w3id.org/mds#dataSubcategory',
  dataModel: 'http://w3id.org/mds#dataModel', // guessed
  geoReferenceMethod: 'http://w3id.org/mds#geoReferenceMethod', // guessed
  transportMode: 'http://w3id.org/mds#transportMode',
  ```

**Comment by omarsilva1** [comment]
I started adding the additional meta information and will continue tomorrow. The progress is given below. I'll also be adding the fields and testing them with the postman collection. 

Some questions:
- Does it make sense to set the id? Isnt this done automatically by the EDC? @efiege 
- I dont think the broker will understand originator and originatorOrganization @SebastianOpriel 

Progress:
- [ ] id: "asset:prop:id", // needs to start with urn:artifact:
- [x] name: "asset:prop:name",
- [ ] contentType: "asset:prop:contenttype",
- [ ] originator: "asset:prop:originator",
- [x] description: "asset:prop:description",
- [x] version: "asset:prop:version",

// our asset properties
- [ ] keywords: "asset:prop:keywords",
- [ ] originatorOrganization: "asset:prop:originatorOrganization",
- [ ] language: 'asset:prop:language',
- [ ] publisher: "asset:prop:publisher",
- [ ] standardLicense: "asset:prop:standardLicense",
- [ ] endpointDocumentation: "asset:prop:endpointDocumentation",

// mds specific asset properties
- [ ] dataCategory: 'http://w3id.org/mds#dataCategory',
- [ ] dataSubcategory: 'http://w3id.org/mds#dataSubcategory',
- [ ] dataModel: 'http://w3id.org/mds#dataModel', 
- [ ] geoReferenceMethod: 'http://w3id.org/mds#geoReferenceMethod', 
- [ ] transportMode: 'http://w3id.org/mds#transportMode',

**Comment by SebastianOpriel** [comment]
I think the originator was intended to represent the owner of the connector. @efiege and @tmberthold shouldn't that be available somehow by the DAT or the web:did? Where is the company name set and validated?

**Comment by richardtreier** [comment]
> I dont think the broker will understand originator and originatorOrganization, can you clarify what this means @richardtreier ?

Originator Organization is the organization name of the customer that we deployed this UI instance for. Because our UI is currently supplying all asset properties, this value is provided via configuration (and is not user editable).

Same for Originator, which is a URL endpoint of the backend of the currently deployed connector. Example from the test bed's `connector-a-ui`'s config: `http://connector-a-controlplane-1:8282/api/v1/ids/data`. Iirc,some protocol/extension requires this for things to work properly.

**Comment by omarsilva1** [comment]
Some notes and questions:
- Is it possible for the UI to follow standard language representation from the ids infomodel (`https://w3id.org/idsa/code/EN` instead of `ISO_639:EN`) ? This would make it way simpler on my end. @richardtreier 
- Are these all the fields? I would expect something like accessUrl or artifact data (byte size, checksum, file name)
- The EDC already has the original id of the resource (with key `http://www.w3.org/2002/07/owl#sameAs`), so I think asset:prop:id is not necessary.
- Same thing for originator, do you know which extensions use this field?
- EndpointDocumentation seems to "crash" the broker without an accessUrl. The resource isnt being shown
