### ISSUE TITLE
Release 7.1.0

### ISSUE THREAD

**Issue by kulgg** [sovity/edc-extensions#720]
# Release

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:

- [x] Release [edc-ui](https://github.com/sovity/edc-ui), this might require several steps: [v2.3.0](https://github.com/sovity/edc-ui/releases/tag/v2.3.0)
- [x] Decide a release version depending on major/minor/patch changes in the CHANGELOG.md.
- [x] Update this issue's title to the new version
- [x] `release-prep` PR:
    - [x] Write or review the current [Productive Deployment Guide](https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/production)
    - [x] Write or review the current [Development Deployment Guide](https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/development)
    - [x] Write or review the current [Local Demo Deployment Guide](https://github.com/sovity/edc-extensions/blob/main/docs/deployment-guide/goals/local-demo)
    - [x] For Major version updates: If we want to continue supporting the old major version:
        - [ ] Keep the old Productive Development Guide in a separate location.
            - [ ] Add a note to the old version about its deprecation status.
            - [ ] Add a Link the old version in the new version for discoverability.
            - [ ] Check all links in the old version.
        - [ ] Keep the old Productive Development Guide in a separate location.
            - [ ] Add a note to the old version about its deprecation status.
            - [ ] Add a Link the old version in the new version for discoverability.
            - [ ] Check all links in the old version.
    - [ ] Update the CHANGELOG.md.
        - [x] Add a clean `Unreleased` version.
        - [x] Add the version to the old section.
        - [x] Add the current date to the old version.
        - [x] Check the commit history for commits that might be product-relevant and thus should be added to the
          changelog. Maybe they were forgotten.
        - [x] Write or review the `Deployment Migration Notes` section, check the commit history for changed / added
          configuration properties.
        - [x] Write or review a release summary.
        - [x] Write or review the compatible versions section.
        - [x] Add a link to the EDC UI Release to the "EDC UI" section.
        - [x] Add a link to the EDC UI Release Deployment Migration Notes from the Deployment Migration section if the EDC UI has Deployment Migration Notes.
        - [x] Remove empty sections from the patch notes.
    - [x] Replace the existing `docker-compose.yaml` with `docker-compose-dev.yaml`.
    - [x] Set the version for `EDC_IMAGE` of
      the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
    - [x] Set the version for `TEST_BACKEND_IMAGE` of
      the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
    - [x] Set the UI release version for `EDC_UI_IMAGE` of
      the [docker-compose's .env file](https://github.com/sovity/edc-extensions/blob/main/.env).
    - [x] If the core EDC version changed, update the `openapi.yaml`.
    - [x] Update the Postman Collection if required.
    - [x] Merge the `release-prep` PR.
- [x] Wait for the main branch to be green.
- [x] Test the release `docker-compose.yaml` with `RELEASE_EDC_IMAGE=ghcr.io/sovity/edc-dev:latest`.
    - [x] Ensure with a `docker ps -a` that all containers are healthy, and not `healthy: starting` or `healthy: unhealthy`.
- [ ] Test the postman collection against that running docker-compose.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [ ] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [ ] Revisit the changed list of tasks and compare it
  with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/edc-extensions/blob/main/.github/ISSUE_TEMPLATE/release.md).
  Propose changes where it
  makes sense.
- [x] Close this issue.

**Comment by tmberthold** [comment]
Just a note to an entry in the changelog:
`Added JWKS-Extension, which provides an endpoint in the default API, that returns the JWKS of the connector.`
https://github.com/sovity/edc-extensions/blob/main/CHANGELOG.md

I don't know if the following shouldn't be done before the release in context with the above change: https://github.com/sovity/PMO-Software/issues/387

Otherwise moving the extension in context of PMO-Software 387 later would immediately result in a major change for edc-extensions and on the other hand a released CE would have a feature that possibly shouldn't be there.
