### ISSUE TITLE
Adapt both the Connector UI and Broker UI

### ISSUE THREAD

**Issue by ununhexium** [sovity/edc-extensions#852]
## Description
Please refer to https://github.com/sovity/edc-extensions/issues/679 for complete context. 

The backend implemented 4 new fields and removed 4 previously existing fields regarding custom properties.

This affects the UI API and can cause breaks if the UI used the old fields.

## Tasks
- [x] Check whether any UI change is required to make this work with the new Json properties.
- [x] If required, do the necessary adaptions.
- [ ] Release new version of edc-ui

**Comment by AbdullahMuk** [comment]
@kulgg I understand from @ununhexium that we need to do the necessary checks before the next edc-ui release. 

The next edc-ui release is anticipated for Friday 22.03 as part of https://github.com/sovity/PMO-Software/issues/798

Please prioritize the necessary checks as soon as possible.
